name: Shopkpr cli test 

on:
  ## run only on master branch on every push
  push : 
    branches : ["master"]

jobs:
  build:
    ## uses a matrix strategy for tesing on diff combinations
    runs-on: ${{ matrix.platform }}
    ## to continue the action on failing at some specific platform
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      ## for running at max 3 jobs 
      max-parallel: 3
      # ## Do not fail the action after any of the job failed
      # fail-fast : false
      matrix:
        ## defining diff platforms to be tested
        platform: [ubuntu-latest, macos-latest, windows-latest]
        ## defining diff versiosn of python to test
        python-version: [3.5, 3.6, 3.7]
        experimental : [false]
        include : 
          - python-version : 3.7
            platform : ${{matrix.platform}}
            ## exempting this version so that the action dont failed on failing at this job
            experimental : true

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions

      - name: Run tox targets for ${{ matrix.python-version }}
        run: "python -m tox"
        env:
          PLATFORM: ${{ matrix.platform }}